#define SOKOL_NO_ENTRY
#define SOKOL_APP_IMPL
#define SOKOL_AUDIO_IMPL
#define SOKOL_GLUE_IMPL
#include "sokol_app.h"
#include "sokol_audio.h"
#include "sokol_gfx.h"
#include "sokol_glue.h"
#include "sokol_log.h"
